# Generated by Django 6.0.4 on 2026-06-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('caregiver', 'Caregiver'), ('tutor', 'Tutor')]),
        ),
    ]
