# Generated by Django 6.0.4 on 2026-05-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerservice',
            name='student_name',
            field=models.CharField(default=1111),
            preserve_default=False,
        ),
    ]
