# Generated by Django 6.0.4 on 2026-05-07 03:10

import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_registerservice_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=services.models.generate_random_code, max_length=8, unique=True)),
                ('caregiver_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.registerservice')),
            ],
        ),
    ]
