# Generated by Django 6.0.4 on 2026-05-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.DateTimeField(),
        ),
    ]
