# Generated by Django 6.0.4 on 2026-05-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_session_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
