# Generated by Django 6.0.4 on 2026-05-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
