# Generated by Django 6.0.4 on 2026-05-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_session_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.IntegerField(blank=True, choices=[('30 Minutes', 30), ('45 Minutes', 45), ('60 Minutes', 60), ('75 Minutes', 75), ('90 Minutes', 90)], null=True),
        ),
    ]
