# Generated by Django 6.0.4 on 2026-06-09 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_session_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(30, '30 Minutes'), (45, '45 Minutes'), (60, '60 Minutes'), (75, '75 Minutes'), (90, '90 Minutes')], null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='note',
            field=models.CharField(blank=True, null=True),
        ),
    ]
