# Generated by Django 6.0.4 on 2026-06-12 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_service_tutor_alter_session_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='caregiver_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='student_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='tutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'tutor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='year',
            field=models.IntegerField(choices=[(7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], default=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 Minutes'), (45, '45 Minutes'), (60, '60 Minutes'), (75, '75 Minutes'), (90, '90 Minutes')], default=60),
            preserve_default=False,
        ),
    ]
