# Generated by Django 6.0.4 on 2026-06-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_caregiver_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
