# Generated by Django 6.0.4 on 2026-06-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_session_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('file', models.FileField(upload_to='documents')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
