# Generated by Django 6.0.4 on 2026-07-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_servicedocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.AddField(
            model_name='service',
            name='documents',
            field=models.ManyToManyField(blank=True, through='services.ServiceDocument', to='services.document'),
        ),
    ]
