# Generated by Django 6.0.7 on 2026-07-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_rename_subject_service_subjects_service_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='year',
            field=models.IntegerField(blank=True, choices=[(7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')]),
        ),
    ]
