# Generated by Django 6.0.7 on 2026-07-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_service_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='year',
            field=models.IntegerField(blank=True, choices=[(7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], null=True),
        ),
    ]
