# Generated by Django 6.0.7 on 2026-07-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_service_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(default=142151251),
            preserve_default=False,
        ),
    ]
