# Generated by Django 6.0.7 on 2026-07-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_remove_service_documents_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
