# Generated by Django 6.0.7 on 2026-07-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_resource_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=3),
            preserve_default=False,
        ),
    ]
