# Generated by Django 6.0.7 on 2026-07-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_session_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
