# Generated by Django 6.0.7 on 2026-07-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_alter_session_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
