# Generated by Django 6.0.7 on 2026-07-30 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_session_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='subject_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.subjectservice'),
            preserve_default=False,
        ),
    ]
