# Generated by Django 6.0.7 on 2026-07-31 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_session_subject_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='subject_service',
            new_name='subject',
        ),
    ]
