# Generated by Django 6.0.7 on 2026-08-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_session_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
