# Generated by Django 6.0.7 on 2026-08-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_session_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
