# Generated by Django 6.0.7 on 2026-08-13 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_document_creater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='creater',
            new_name='creator',
        ),
    ]
