# Generated by Django 6.0.7 on 2026-07-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_description_review_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='category',
        ),
        migrations.RemoveField(
            model_name='reviewcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='reviewcategory',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ReviewCategory',
        ),
    ]
