# Generated by Django 6.0.7 on 2026-08-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.CharField(),
        ),
    ]
